<<<<<<< HEAD
=======
---
>>>>>>> dac3d78a8450453da532dfad111db247b8801f7d
# Dependencies install
- hosts: appServer
  become: yes
  become_user: root
  become_method: sudo
  tasks:
<<<<<<< HEAD
    - name: install epel-release
      yum:
        name:
          - epel-release
        state: present
    - name: update
      yum:
        name:
          - "*"
        state: latest  
    - name: Install python3
      yum:
        name:
          - python36
        state: present
=======
    - name: Install python3
      yum:
        name:
          - python-setuptools
          - python36
          - python36-pip
          - python36-devel
        state: present

>>>>>>> dac3d78a8450453da532dfad111db247b8801f7d
